### ISSUE TITLE
totd time it takes to pull data

### ISSUE THREAD

**Issue by nemaides** [GreepTheSheep/discord-trackmania.io#90]
First of, thanks for your work Greep.

I was just wondering if it's by design that the bot pulls the totd information later than posted on tm.io, as to not send too many requests? 
I'm just experiencing the bot giving notifications 3-5 minutes late, and we all know how valuable those minutes can be, if you miss the qualifying ;)

Or if the issue simply is the tm.io api being slow at pushing the data.

**Comment by GreepTheSheep** [comment]
Based on this function: https://github.com/GreepTheSheep/node-trackmania.io/blob/develop/src/client/Client.js#L101-L118

At 7pm it starts making a new request and checks if the date corresponds, if not then it will do another one 30 seconds later.

Plus Trackmania.io can take some time to fetch the TOTD because of its caching system (mainly, the new TOTD appears 1 or 2 minutes after 7pm).

So yeah, it's totally normal 😛
